# Generated by Django 5.1.3 on 2024-12-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweather',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
