# Generated by Django 3.1.13 on 2024-12-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0004_alter_cityweather_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityweather',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='cityweather',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
